# Generated by Django 3.0 on 2020-04-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200429_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('BC', 'BASIC'), ('BB', 'BIG BOSS'), ('NN', 'NONE')], default='NN', max_length=2),
        ),
    ]
